name: Build then Publish via FTP

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Start:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2
      
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm install
    - run: git checkout package-lock.json
    - run: npm run build --if-present
      
    - name: List output files
      run: find . -maxdepth 2 -type d -exec ls -ld "{}" \;

    - name: FTP Deploy Action
      uses: SamKirkland/FTP-Deploy-Action@3.1.1
      with:
        ftp-server: ${{ secrets.FTP_IRECIPE_HOST }}
        ftp-username: ${{ secrets.FTP_IRECIPE_USERNAME }}
        ftp-password: ${{ secrets.FTP_IRECIPE_PASSWORD }}
        local-dir: dist  
